spring.application.name=budgetingIncomesExpenses
spring.datasource.url=jdbc:postgresql://localhost:5432/bie_dev
spring.datasource.username=bie_dev
spring.datasource.password=biepassworddev
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect